apiVersion: apps/v1
kind: Deployment
metadat:
  name: auth
  labels:
    app: auth

spec:
  replicas: 2
  selector:
    matchLables:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  templates:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: princewillingoo/auth
        ports:
          - containerPort: 5000
        envFrom:
          - configMapRef:
              name: auth-configmap
          - secretRef:
              name: auth-secret 


